# Generated by Django 2.2 on 2019-06-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=32)),
            ],
        ),
    ]
